### 숙소 검색 (LIKE 검색)
GET http://localhost:8080/v1/accommodations?keyword=하얏트 서울
Content-Type: application/json

### 숙소 검색 (전문 검색)
GET http://localhost:8080/v1/accommodations/v2?keyword=하얏트 서울
Content-Type: application/json
