### 숙소 검색 (keyword, checkIn, checkOut, capacity + page/size)
@keyword = 강릉
@checkIn = 2025-11-07
@checkOut = 2025-11-09
@capacity = 2

GET http://localhost:8080/v1/accommodations/search?keyword={{keyword}}&checkIn={{checkIn}}&checkOut={{checkOut}}&
    capacity={{capacity}}
Content-Type: application/json